openapi: '3.0.1'

info:
  title: Geo API
  description: API specification for service identifying London area users
  version: '1.0'

servers:
  - url: 'http://localhost:8080'

paths:
  /v1/users/london/area:
    get:
      operationId: getPeopleInLondonArea
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeopleDto'
components:
  schemas:
    PeopleDto:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        ip_address:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double

